services:
    panamby_rabbit:
        image: rabbitmq:3.8.22-management
        container_name: panamby_rabbit
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=123
            - RABBITMQ_DEFAULT_VHOST=panamby
            
    panamby_mongo:
        image: mongo:3.6.23
        container_name: panamby_mongo
        restart: always
        environment:            
            - MONGO_INITDB_DATABASE=panamby
            - MONGO_INITDB_USER=root
            - MONGO_INITDB_PASS=root
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - 27017:27017
            
    panamby_redis:
        image: redis:7.0.0
        container_name: panamby_redis
        restart: always
        ports:
            - 6379:6379
            
    imusica_redisinsight:
        image: redislabs/redisinsight:latest
        container_name: panamby_redisinsight
        restart: always
        ports:
          - 8001:8001
        volumes:
          - ./redisinsight:/db
        depends_on:
            - panamby_redis
            
    panamby_localstack:
        image: localstack/localstack:latest
        container_name: panamby_aws
        environment: 
          - AWS_DEFAULT_REGION=sa-east-1
          - EDGE_PORT=4566
          - SERVICES=lambda,s3,dynamodb
          - DYNAMODB_SHARE_DB=1
          - KINESIS_PROVIDER=kinesalite
        ports: 
          - '4566-4583:4566-4583'
        volumes: 
          - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"         